### ISSUE TITLE
in Chrome, ctrl+f does not position to text inside perfect-scrollbar area

### ISSUE THREAD

**Issue by BenArunski** [utatti/perfect-scrollbar#467]
JSFiddle: https://jsfiddle.net/xv0rrxv3/8/
Steps to reproduce: 
- open fiddle in Chrome
- press Ctrl+f and search for 'Hello'
- press down-arrow or ENTER again to find 'Hello' in the perfect-scrollbar area
- Chrome normally positions to text when you search and find it; it does not do so in the perfect-scrollbar area.

Thank you so much for your help!

**Comment by noraesae** [comment]
Just for information, I'm sure this used to work. As I remember, at that time a `scroll` event was fired when a text is searched even in a `overflow: hidden` container. I've just tried it in the fiddle, and it didn't work well. I guess there has been a browser fix for it.

For the time being, I'm not sure there can be an effective workaround for this.

**Comment by zomp** [comment]
Hi @noraesae, it might work even now, but specific conditions must be met.

I have been experiencing this issue on Kubuntu/**Firefox** since I started to use perfect-scrollbar more than a year ago and I haven't spot changes in this behaviour. Usually Ctrl+F does not work, but if I focus the scrollable area somehow (or st like that), it starts to work fine. Unfortunately I haven't been able to identify the conditions enabling Ctrl+F.

Maybe if we identify the conditions, we will be able to make it work reliably.

**Comment by BenArunski** [comment]
Thank you for the responses!  I played around some more, and I was not able to find any conditions under which Ctrl+F positions to the found text (checked on Chrome and Firefox).

**Comment by zomp** [comment]
I made it work only in Firefox by wrapping the text by `<textarea>`: [https://jsfiddle.net/xv0rrxv3/24/](https://jsfiddle.net/xv0rrxv3/24/).

**Comment by paralin** [comment]
Can we fix this?

**Comment by paralin** [comment]
?

**Comment by paralin** [comment]
??

**Comment by rolandtoth** [comment]
On Chrome I was able to create a fix:

1. set container to overflow: scroll
2. set container css ::-webkit-scrollbar { display: none; } (or width: 0)

After this, searching with ctrl+F jumps to the results. Perhaps other browsers could be targeted as well.

**Comment by noraesae** [comment]
@rolandtoth 's solution is actually quite nice solution for scrolling, but as I know hiding scrollbar is only supported in webkit browsers.

**Comment by rolandtoth** [comment]
You seem to be right. One solution could be playing with container padding and margin, but that's also error-prone.

**Comment by pedro380085** [comment]
+1

**Comment by utatti** [comment]
Having `overflow: hidden` is by design, to emulate scrolls. I may not choose to use separate implementation only for webkit browsers, I'd leave it to user's choice as it can be done quite simply by checking UA in user script.

I've added this to known [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats).

**Comment by themadsens** [comment]
For IE11 and Edge, it seems `-ms-overflow-style: none` can be used. Chrome +  Safari + Opera + Midori + IE11 + Edge covered then?

**Comment by VictorSholomickiy** [comment]
> On Chrome I was able to create a fix:
> 
> 1. set container to overflow: scroll
> 2. set container css ::-webkit-scrollbar { display: none; } (or width: 0)
> 
> After this, searching with ctrl+F jumps to the results. Perhaps other browsers could be targeted as well.

Hello, could you please give me more information about for which class I should add styles? I think I tried every variant and it doesn't work for me...
