### ISSUE TITLE
Scroll slicks in IE

### ISSUE THREAD

**Issue by alonshmiel1** [utatti/perfect-scrollbar#604]
Hi,

There is a bug in IE that the scroll slicks:
http://plnkr.co/edit/vJjyq8JeUFLD1fzM2LRj?p=preview

As I read, there was an open issue concerning this bug:
https://github.com/noraesae/perfect-scrollbar/issues/160

I am not sure but I think you uploaded two fixes for that.

Unfortunately, I didn't see that you push it to master.

Please let me know if I'm right.

Thank you,
Alon.

Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [x] Provide a page or source code where the issue can be checked

**Comment by danielordonez** [comment]
Looking forward for a fix to this issue too, I really like perfect scrollbar but this issue really compromises my ux

**Comment by tkorsa** [comment]
I haven't tried this but what about using translate instead of top. I have nothing to back this up but maybe it's jumping around because of top/right/bottom/left lack of sub pixel animation.

Also, TRBL uses more paint frames than translate.

I could do a PR but I have no way to test on IE atm. :crying_cat_face:

**Comment by tkorsa** [comment]
Maybe something like

**default-settings.js**
```
{
  ...
  userCss3: true
}
```

**update-geometry.js** *line ~48*
```
if (i.settings.useCss3) {
  dom.css(i.scrollbarX, {transform: 'translateX(' + i.scrollbarXLeft + 'px)', width: i.scrollbarXWidth - i.railBorderXWidth});
  dom.css(i.scrollbarY, {transform: 'translateY(' + i.scrollbarYTop + 'px)', height: i.scrollbarYHeight - i.railBorderYWidth});
} else {
  dom.css(i.scrollbarX, {left: i.scrollbarXLeft, width: i.scrollbarXWidth - i.railBorderXWidth});
  dom.css(i.scrollbarY, {top: i.scrollbarYTop, height: i.scrollbarYHeight - i.railBorderYWidth});
}
```

**Comment by utatti** [comment]
It's basically because of IE bug concerning synchronous update on scroll properties. IE renders scroll properties asynchronously, even though it's updated in sync with other styles.

I think using CSS transform only for IE is not a way to go, as it must result in more branch and eventually implementation issues. As I mentioned in the original issue, I may close this. This time I will add some info in README and Wiki too.
