### ISSUE TITLE
Choppy/Unnatural scroll when using wheelPropogration and touch pads

### ISSUE THREAD

**Issue by rohmann** [utatti/perfect-scrollbar#639]
When you reach the bottom of a scrollable area, continuing to scroll down is laggy until your mouse leaves the perfect scrollbar container.

Example 1: https://jsfiddle.net/h0t189v5/
Example 2: https://jsfiddle.net/1zwk1e4m/

For some reason is seems worse when more content is on the screen.

**Comment by itsOgden** [comment]
@rohmann are you sure it's the bottom of the scrollable area that's causing that issue? I'm just wondering because I have this exact problem with all scrolling on Windows, but perfectly silky scrolling on OSX. I'm trying to figure out if it's a related issue or two separate ones with similar side effects.

**Comment by kennydp** [comment]
I have the same issue on my mac trackpad. I think the cause is the `shouldPreventDefault` function in the [mouse-wheel.js file](https://github.com/OTA-Insight/perfect-scrollbar/blob/master/src/js/plugin/handler/mouse-wheel.js). I tested it out and when both `deltaX` and `deltaY` are not 0 you return true, which means you will call `stopPropagation` and `preventDefault`. I think you should still check to see if you have reached the start/end of the container while scrolling, because the event should still be propagated in that case.

**Comment by utatti** [comment]
As @kennydp mentioned, it's the problem of `shouldPreventDefault` in mousewheel handler. The logic itself seems fine, but I think it's a bit rigid.

**Comment by konradjurk** [comment]
I noticed this too. Is it fixable?
