### ISSUE TITLE
Click and drag scrollbar and release mouse outside scroll area will trigger a click on document.

### ISSUE THREAD

**Issue by chnldw** [utatti/perfect-scrollbar#672]
Click and drag scrollbar and release mouse outside scroll area will trigger a click on document.
While browser's native scrollbar would not trigger a click. Is that possible to fix this?

JSFiddle: [https://jsfiddle.net/gbfLazpx/975/](https://jsfiddle.net/gbfLazpx/975/)

**Comment by andrewtibbetts** [comment]
This behavior also happens when you release mouse over the rail. It will trigger a click on the rail which in IE and Chrome makes the scrollbar jump to the bottom.

![perfect-scrollbar-issue](https://user-images.githubusercontent.com/296908/29463634-0331ea8e-83f9-11e7-905e-061f5dcb25c1.gif)

**Comment by utatti** [comment]
We can prevent an event from being propagated or doing default behaviour, but cannot prevent other events in the same level. That's why we cannot do anything on document click. Basically there is no easy (or even hard) way to prevent document click from being fired.

However @andrewtibbetts's example seems like fixable. I will upload a fix for it.
