### ISSUE TITLE
how to make this work for position:fixed elements?

### ISSUE THREAD

**Issue by sasukepatel** [utatti/perfect-scrollbar#677]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by utatti** [comment]
- If you mean `position: fixed` for container, perfect-scrollbar works without any modification. Please beware that the container should be statically sized with `width` and `height` to be scrolled.
- If you mean `position: fixed` for scrollbars, unfortunately it is not possible because of implementation issue. I suggest using browser-native scrollbar or looking into other scrollbar plugins.
