### ISSUE TITLE
Is there a way to move the x rail to the top of the scrolled element?

### ISSUE THREAD

**Issue by catmanjan** [utatti/perfect-scrollbar#683]
Couldn't find how to do so in the FAQ, but I suspect it would be a desirable feature for lots of people.

**Comment by utatti** [comment]
Just use `top` instead of `bottom` here:

- https://github.com/utatti/perfect-scrollbar/blob/next/css/perfect-scrollbar.css#L21

There is an example for this case, `scrollbars-on-the-opposite-side.html`. The example's JS is out of date, but the part which matters is actually `<style>`. The current branch is under heavy construction, and I will fix examples after that.
