### ISSUE TITLE
Webpack issue with require('perfect-scrollbar')

### ISSUE THREAD

**Issue by tegomass** [utatti/perfect-scrollbar#697]
Hi,

I faced an issue when using PerfectScrollbar with Webpack.

As your doc says, I installed perfect-scrollbar using : 
`$ npm install perfect-scrollbar`

Then I use it in my script file, so I used this command : 
`const PerfectScrollbar = require('perfect-scrollbar');`
 
But I've got this error message : 
`Uncaught ReferenceError: PerfectScrollbar is not defined`

My script file have just the minimal code below : 

```
const PerfectScrollbar = require('perfect-scrollbar');
const ps = new PerfectScrollbar('#container');
```

However, If I use `import PerfectScrollbar from 'perfect-scrollbar';` instead of `require`, it works perfectly !!
I wanted to report this issue tho... But maybe I miss understood something ?

**Comment by utatti** [comment]
Will check

**Comment by utatti** [comment]
I've just tested it out and it seems like working. What is your webpack config? Is there any repository where I can look into the problem?

**Comment by tegomass** [comment]
Hi,

I've uploaded the very simple project using webpack and perfect-scroll bar, please take a look here : 
https://github.com/tegomass/perfect-scrollbar-webpack-demo

Just do a ` npm install ` then ` webpack ` on the directory.
Open the `index.html` file.

Comment/uncomment the line below to see the difference:
`
//import PerfectScrollbar from 'perfect-scrollbar';
`

With the require method, I have an error about the Constructor (on the chrome devtools console)

**Comment by utatti** [comment]
Related issue:

- https://github.com/webpack/webpack/issues/1979

In short, webpack will use ES6 module script. 

Perfect-scrollbar provides both CommonJS and ES6 module scripts, with `main` and `module` fields in order. I thought webpack will use CJS for `require` and ESM for `import`, but I was wrong. [Webpack just prioritize `module`](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L112).

So in this case, the solution may be like below:

1. Use ES2015 module import.
2. Use CommonJS, with `.default`:
    `const PerfectScrollbar = require('perfect-scrollbar').default;`
3. Override webpack `resolve` config to prioritize `main` instead of `module`:
    `{ resolve: { mainFields: ['main', 'module'] } }`

I will update README to mention about this. Thanks for your report!

**Comment by kikoseijo** [comment]
You made my day, thanks @utatti

**Comment by dantranv** [comment]
Hi @tegomass, @utatti 
I use import with my webpack and got the same error ReferenceError: "PerfectScrollbar is not defined"
v1.4.0
import PerfectScrollbar from 'perfect-scrollbar';

Any idea?

**Comment by draaslan** [comment]
> Hi @tegomass, @utatti
> I use import with my webpack and got the same error ReferenceError: "PerfectScrollbar is not defined"
> v1.4.0
> import PerfectScrollbar from 'perfect-scrollbar';
> 
> Any idea?

`window.PerfectScrollbar = require('perfect-scrollbar');`

I did it after 3 hours of trying and works now. You can try :)

**Comment by NikitaIT** [comment]
What about a normal esm release? this makes the library literally obsolete, because it requires mandatory transpilation since 2015

**Comment by pathaksa** [comment]
This worked for me:

window.PerfectScrollbar = require('perfect-scrollbar').default;
