### ISSUE TITLE
Request for Sass file in repo

### ISSUE THREAD

**Issue by KickinAss** [utatti/perfect-scrollbar#710]
Hi,
in the old versione, there is a Sass file with some variables in order to style the scrollbars. 

It was usefull for me, why not bring it back?

**Comment by utatti** [comment]
I decided to drop Sass for the following reason:

- It results in larger CSS file size
- It results in ineffective CSS, mainly because of unneeded nestings
- It’s difficult for users to modify and build from source. With CSS, it’s just copy and modify.
- It’s small enough, a single-file CSS is good enough for maintainability.

I’m sorry that Sass is no longer provided. Please copy the CSS and modify it directly.
