### ISSUE TITLE
RTL doesn't play fine with "suppressScrollX" option

### ISSUE THREAD

**Issue by arl1nd** [utatti/perfect-scrollbar#713]
I have found a bug which is generally related to RTL direction.

Reproducing the bug is very easy, open **examples/rtl.html** and assign `suppressScrollX: true` option and the scroll will go mad:

[See the video demonstration of this bug](http://drops.laborator.co/CRVt96)

I hope you can fix it.

**Comment by utatti** [comment]
Duplicated: #689 

RTL support was once implemented and thus there an example or some flags in code. However, it has not been maintained for a long time and does not work for the time being. The issue is tracked, but no work is ongoing too. I personally have no domain knowledge of RTL, so I'm waiting for some helps currently. Surely I'll look into it when possible.

**Comment by arl1nd** [comment]
Its interesting that this issue is not appearing in version 0.6.16 so that might help you figure out the issue.
