### ISSUE TITLE
All children scroll out of view when reaching end of scroll extent

### ISSUE THREAD

**Issue by Bilge** [utatti/perfect-scrollbar#737]
By default (with `overflow: auto`) a the scroll extent is defined such that the scrolling ends when the last child is completely scrolled *into* view. However, when using *perfect-scrollbar*, the scrolling ends with the last child is completely scrolled *out of* view!

![untitled-1](https://user-images.githubusercontent.com/470626/34455934-d6837906-ed81-11e7-9b58-079d45c84c97.png)

This screenshot shows the behaviour of the default scrollbar on the left and *perfect-scrollbar* on the right. Both have been scrolled to their maximum extents. Perfect-scrollbar is empty because it allows all its children to be completely scrolled out of view. This behaviour is highly undesirable but there does not seem to be an option to disable it!

**Comment by konradjurk** [comment]
@Bilge Hey, if you've applied [these steps](https://github.com/utatti/perfect-scrollbar#before-using-perfect-scrollbar) from the README and the behavior persists, could you provide a jsfiddle or something similar? :)

**Comment by Bilge** [comment]
Sorry but I didn't end up using this library because I think it has a long way to go before it lives up to its name.

**Comment by konradjurk** [comment]
@Bilge Harsh words, do mind letting us know which library you chose instead that satisfies your usecase? If it is indeed a bug we should adapt this library which will help a lot of people.

Apart from that, the cause of your bug is almost certainly a small configuration thingy.

**Comment by Bilge** [comment]
I ended up rolling my own which still uses native scrolling, but modifies its behaviour to work better with transitions and doesn't scroll the parent window when reaching the extents.

I realize this could possibly be my own fault, but there are shortcomings I haven't listed. Besides [the other ticket I raised](https://github.com/utatti/perfect-scrollbar/issues/736), I don't like the fact that it loses the smooth scrolling animation that native scrolling has on Windows. After becoming accustomed to the pleasantry of smooth scrolling, the jaunty instant relocation is a bit jarring and uncomfortable by comparison. Consequently I no longer have an interest in pursuing usage or improvement of this library at this time, however I may revisit it in future.

**Comment by konradjurk** [comment]
@Bilge Thanks much for the feedback :) Will look into the Windows thingy.

@utatti Do you like Bildge's idea to ease the setup of perfect-scrollbar? Maybe we can ship a default `.container` class or the constructor sets the required style on the parent DOM element?

**Comment by utatti** [comment]
@Bilge Thanks again for your feedback.

About the smooth scrolling, it is impossible to implement the smooth scrolling without timer while using native `scrollTop` and `scrollLeft`. I may not implementing it with timers as it results in performance burden. There are other scrollbar libraries where CSS position or transition is used to emulate scrolls, so if smooth scrolling is needed, they are the ways to go.

@konradjurk About required styles, the only non-optional requirement is `position`, which can be `relative`, `absolute`, `fixed` or whatever. I may let users specify it by themselves, rather than setting it as `relative` ad hoc.

I'm sorry again for perfect-scrollbar not being perfect at all like everything else, not satisfying your needs. I'll work hard for the future when you may revisit :)
